name: 'Kusion Action'
description: 'Kusion Action'
inputs:
  subcommand:  
    description: 'kusion subcommand'
    required: true 
    default: 'apply'
  workDir:  
    description: 'work directory'
    required: false
    default: ''
  settings:  
    description: 'KCL setting files'
    required: false
    default: ''
  arguments:  
    description: 'KCL arguments'
    required: false
    default: ''
  filenames:  
    description: 'KCL files'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subcommand }}
    - ${{ inputs.workDir}}
    - ${{ inputs.settings }}
    - ${{ inputs.arguments }}
    - ${{ inputs.filenames }}
branding:
  icon: 'check-circle'  
  color: 'green'
